#!/bin/bash

PROG=youtube-dl
PROG=yt-dlp

function getName {
   $PROG --get-filename --restrict-filenames -o "$DEST"/'%(title)s.%(ext)s' "$1" | \
     sed 's/_/ /g' | \
     sed 's^/a z/^/a_z/^g'
}

function help {
  if [ "$1" ]; then printf "Error: $1\n\n"; fi
  echo "$( basename $0) - Download videos from various sites, including YouTube."
  echo "Can save video, or can just save audio as mp3 to $MP3_DEST on the local machine."
  echo "Also copies to gojira."
  echo ""
  echo "Usage: $( basename $0) [options] url"
  echo ""
  echo "Options are:"
  echo "  -h       display this message and quit"
  echo "  -v       download video to $VDEST"
  echo "  -V dir   download video to any given directory"
  echo "  -x       download video to $XDEST"
  echo ""
  echo "Last modified 2022-07-24"
  exit 1
}

function isWsl {
  [ "$( cat /proc/version | grep microsoft )" ]
}

CLIP_JAM=/media/mslinn/Clip\ Jam/Music/playlist
if [ -d "$CLIP_JAM" ]; then 
  MP3_DEST="$CLIP_JAM"
elif [ "$mp3s" ]; then 
  MP3_DEST="$mp3s"
elif [ `uname -n` == gojira ]; then
  MP3_DEST="/data/media/mp3s"
else
  MP3_DEST="$HOME/Music/mp3s"
fi

XDEST="$HOME/Videos"
VDEST="$XDEST"
if [ $( isWsl ) ]; then
  if [ -d /mnt/e ]; then DEST_DRIVE=/mnt/e; else DEST_DRIVE=/mnt/c; fi
  VDEST=/mnt/c/Users/Mike\ Slinn/Videos
  XDEST=$DEST_DRIVE/storage/a_z/videos
elif [ `uname -n` == gojira ]; then
  VDEST="/data/media/staging"
  XDEST="/data/a_z/videos"
fi

DEST="$MP3_DEST"
OPTIONS='--extract-audio 
--audio-format mp3 
--audio-quality 3 
--prefer-ffmpeg'
#VERBOSE=--verbose

ACTION=mp3
while getopts "dhvV:x\?" opt; do
   case $opt in
     d ) echo "Debug mode enabled"
         set -xv 
         ;;
       
	   V ) echo "Keep video enabled"
         ACTION=video
	       DEST="$OPTARG"
         OPTIONS=--keep-video
         ;;

	   v ) DEST="$VDEST"
	       echo "Downloading video to $DEST"
         ACTION=video
         OPTIONS=--keep-video
         ;;
       
	   x ) DEST="$XDEST"
	       echo "Downloading video to $DEST"
         ACTION=video
         OPTIONS=--keep-video
         if [ "$1" == *pornhub.com* ]; then OPTIONS="$OPTIONS -ss 3"; fi
		     ;;
       
	   * ) help ;;
   esac
done
shift $(($OPTIND-1))

if [ -z "$1" ]; then help "Please provide a URL"; fi

NAME="$( getName "$1" )"

# See https://github.com/rg3/youtube-dl/blob/master/README.md#readme
nice $PROG $VERBOSE $OPTIONS \
  --restrict-filenames \
  --no-part \
  --output "$NAME" "$1"

if [ "$ACTION" == mp3 ]; then
  MP3_NAME="${NAME/.webm/.mp3}"
  MP3_NAME="${MP3_NAME/.mp4/.mp3}"

  #mp3tag "$MP3_NAME"
  #S3_NAME="s3://musicmslinn/$(basename "$MP3_NAME")"
  #echo "Uploading to $S3_NAME"
  #aws s3 cp "$MP3_NAME" "$S3_NAME"
  
  echo "Copying to gojira..."
  scp "$MP3_NAME" mslinn@gojira:/data/media/mp3s/
elif [ "$ACTION" == video ] && [ `uname -n` != gojira ]; then
  echo "Copying to gojira..."
  scp "$NAME" mslinn@gojira:/data/a_z/videos/
fi

